In [1]:
from pyspark.sql import SparkSession

In [2]:
spark = SparkSession.builder.appName('aggs').getOrCreate()

In [3]:
df = spark.read.csv('/FileStore/tables/sales_info.csv', inferSchema=True, header=True)

In [4]:
df.show()

In [5]:
df.printSchema()

In [6]:
df.groupBy('Company').mean().show()

In [7]:
df.groupBy('Company').count().show()

In [8]:
df.agg({'Sales': 'sum'}).show()

In [9]:
group_data = df.groupby('Company')

In [10]:
group_data.agg({'Sales': 'max'}).show()

In [11]:
from pyspark.sql.functions import countDistinct, avg, stddev

In [12]:
df.select(countDistinct('Sales')).show()

In [13]:
df.select(countDistinct('Company')).show()

In [14]:
spark.sql('SELECT COUNT(DISTINCT Company) FROM sales_info_csv').show()

In [15]:
df.select(avg('Sales').alias('Avg Sales')).show()

In [16]:
df.select(stddev('Sales')).show()

In [17]:
from pyspark.sql.functions import format_number

In [18]:
sales_std = df.select(stddev('Sales').alias('Sales_std')).select(format_number('Sales_std', 2).alias('Sales_std')).show()

In [19]:
df.show()

In [20]:
df.orderBy("Sales").show()

In [21]:
df.orderBy(df['Sales'].desc()).show()