In [1]:
from pyspark.sql import SparkSession

In [2]:
spark = SparkSession.builder.appName('miss').getOrCreate()

In [3]:
df = spark.read.csv('/FileStore/tables/ContainsNull.csv', header=True, inferSchema=True)

In [4]:
df.show()

In [5]:
df.na.drop().show()

In [6]:
df.na.drop(thresh=2).show()

In [7]:
df.na.drop(how='all').show()

In [8]:
df.na.drop(subset=['Sales']).show()

In [9]:
df.na.fill('FILL VALUE').show()

In [10]:
df.na.fill(0).show()

In [11]:
df.na.fill('No Name', subset=['Name']).show()

In [12]:
from pyspark.sql.functions import mean

In [13]:
mean_val = df.select(mean(df['Sales'])).collect()

In [14]:
mean_val

In [15]:
mean_sales = mean_val[0][0]

In [16]:
df.na.fill(mean_sales, ['Sales']).show()

In [17]:
df.na.fill(df.select(mean(df['Sales'])).collect()[0][0], subset=['Sales']).show()