In [1]:
from pyspark.sql import SparkSession

In [2]:
spark = SparkSession.builder.appName('Basics').getOrCreate()

In [3]:
df = spark.read.json("/FileStore/tables/people.json")

In [4]:
df.show()

In [5]:
df.printSchema()

In [6]:
df.columns

In [7]:
df.describe()

In [8]:
df.describe().show()

In [9]:
from pyspark.sql.types import StructField, StringType, IntegerType, StructType

In [10]:
# True means NULL True. so its okay to have null fields
data_schema = [StructField('age', IntegerType(), True),
               StructField('name', StringType(), True),
              ]

In [11]:
final_struc = StructType(fields=data_schema)

In [12]:
df = spark.read.json('/FileStore/tables/people.json', schema=final_struc)

In [13]:
df.printSchema()

In [14]:
df.show()

In [15]:
df.select('age').show()

In [16]:
df.head(2)

In [17]:
df.select(['age', 'name']).show()

In [18]:
df.withColumn('double_age', df['age']*2).show()

In [19]:
df.show()

In [20]:
df.withColumnRenamed('age', 'my_new_age').show()

In [21]:
df.show()

In [22]:
df.createOrReplaceTempView('people')

In [23]:
result = spark.sql("SELECT * FROM people")

In [24]:
result.show()

In [25]:
new_results = spark.sql("SELECT * FROM people WHERE age=30")

In [26]:
new_results.show()